# tell docker what version of the docker-compose.yml were using
version: '3.5'

services:
  #Nginx Service
  nginx:
    build: 
      context: ./nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./symfony:/code
      - ./nginx/conf.d:/etc/nginx/conf.d
    tty: true
    restart: always
    networks:
      - web-network
    depends_on:
      - php
      - db
  #PHP-FPM Service
  php:
    build: 
      context: ./php-fpm
    container_name: php
    volumes:
      - ./symfony:/code
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.220.1"
      PHP_IDE_CONFIG: "serverName=Docker"
    tty: true
    restart: always
    networks:
      - web-network
  #Angular-node Service
  node:
    build: node
    container_name: angular
    ports:
      - 4200:4200
    volumes:
      - ./angular:/frontend
    tty: true
    restart: always
    command:
      - /bin/sh
      - -c
      - |
        cd /frontend && npm start
    expose:
      - 4200
    networks:
      - web-network
#Postgres Service
  db:
    container_name: postgres_db
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: always
    tty: true
    networks:
      - web-network

#Docker Networks
networks:
  web-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28

#Volumes
volumes:
  dbdata:
    driver: local

##MySQL Service
#  db:
#    image: mysql:5.7.22
#    container_name: mysql_db
#    ports:
#      - "3306:3306"
#    volumes:
#      - dbdata:/var/lib/mysql
#      - ./mysql/my.cnf:/etc/mysql/my.cnf
#    environment:
#      MYSQL_DATABASE: ${DB_NAME}
#      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
#      MYSQL_USER: ${DB_USER}
#      MYSQL_PASSWORD: ${DB_PASSWORD}
#      SERVICE_TAGS: dev
#      SERVICE_NAME: mysql
#    restart: always
#    tty: true
#    networks:
#      - web-network