# tell docker what version of the docker-compose.yml were using
version: '3.5'

services:
  #Nginx Service
  nginx:
    build: 
      context: ./nginx
    ports:
      - 80:80
      - 443:443
    tty: true
    container_name: nginx
    volumes:
      - ./symfony:/code
      - ./nginx/conf.d:/etc/nginx/conf.d
    working_dir: /code
    restart: always
    networks:
      - web-network
    depends_on:
      - php
  #PHP-FPM Service
  php:
    build: 
      context: ./php-fpm
    tty: true
    container_name: php
    restart: always
#    ports:
#      - 4201:4200
    volumes:
      - ./symfony:/code
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.220.1"
      PHP_IDE_CONFIG: "serverName=Docker"
    networks:
      - web-network
  #Angular-node Service
  node:
    build: node
    container_name: angular
    ports:
      - 4200:4200
    volumes:
      - ./angular:/frontend
    tty: true
    restart: always
    command:
      - /bin/sh
      - -c
      - |
        cd /frontend && npm start
    expose:
      - 4200
    networks:
      - web-network
#MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_ROOT_PASSWORD: 123
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - web-network

#Docker Networks
networks:
  web-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28
#Volumes
volumes:
  dbdata:
    driver: local