<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEDWQGNY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEDWQGNY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEDWQGNY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEDWQGNY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEDWQGNY\App_KernelDevDebugContainer([
    'container.build_hash' => 'EDWQGNY',
    'container.build_id' => 'cdc6ebdf',
    'container.build_time' => 1579302090,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEDWQGNY');
